name: Build Nova SDK Dumper DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      # /O2: Hız ve optimizasyon, /Oi: intrinsic fonksiyonlar (AV imzasını bozar)
      # /Ot: Hız için kod boyutu, /MT: Statik kütüphane bağlama
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        
    - name: Build DLL with CMake
      run: |
        cmake --build build --config Release -- /p:CL_CXXFlags="/O2 /Oi /Ot /MT /D_USRDLL /D_WINDLL"

    - name: Upload Compiled DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NovaDumper-x64
        path: build/Release/NovaDumper.dll
        
